version: '3'

services:
  db:
    image: postgres:9.6.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5431:5432"
    volumes:
      - mmt-postgres:/var/lib/postgresql/data
  
  #redis:
  # image: redis:3.0.5
  # expose:
  #   - '6379'
  #  volumes:
  #    - mmt-redis:/var/lib/redis/data
  
  mmt:
    build: .
    depends_on:
      - db
    volumes:
      - .:/mmt
      - bundle:/usr/local/bundle
    entrypoint: docker/entrypoint.sh
    environment:
      DATABASE_URL: db
    ports:
      - "3000:80"

  #sidekiq:
  #  build: .
  #  command: bundle exec sidekiq -C config/sidekiq.yml
  #  links:
  #    - postgres
  #      #    - redis
  #  volumes:
  #    - .:/mmt
  #  env_file:
  #    - .mmt.env
volumes:
  mmt-postgres:
  bundle:
