postgres:
  image: postgres:9.6.5
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 
  ports:
    - '5432:5432'
  volumes:
    - mmt-postgres:/var/lib/postgresql/data

#redis:
#  image: redis:3.0.5
#  ports:
#    - '6379:6379'
#  volumes:
#    - mmt-redis:/var/lib/redis/data

mmt:
  build: .
  links:
    - postgres
      #    - redis
  volumes:
    - .:/mmt
  ports:
    - '8000:8000'
  env_file:
    - .mmt.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
      #    - redis
  volumes:
    - .:/mmt
  env_file:
    - .mmt.env
